version: "3.8"
services:
  telegram-bot:
    image: unaimillan/telegram-bot
    restart: on-failure
    volumes:
      - bot-storage:/app/storage
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
        max-file: "10"

volumes:
  bot-storage:
